name: dfn
version: 0.2.2
repository: https://github.com/Luckey-Elijah/dfn
description: Use Dart as your scripting language, and register scripts from anywhere.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^0.13.6
  mason_logger: ^0.2.4
  meta: ^1.9.1
  path: ^1.8.3
  pub_semver: ^2.1.4

dev_dependencies:
  apealed_analysis: ^0.0.1
  mocktail: ^0.3.0
  test: ^1.24.3

executables:
  dfn:
