name: dfn
description: Use Dart as your scripting language, and register scripts from anywhere.
version: 0.0.1
repository: https://github.com/Luckey-Elijah/dfn

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.3.1
  collection: ^1.17.1
  mason_logger: ^0.2.4
  path: ^1.8.3
  pubspec_parse: ^1.2.3

dev_dependencies:
  apealed_analysis: ^0.0.1

executables:
  dfn:
