name: dfn
version: 0.0.2
repository: https://github.com/Luckey-Elijah/dfn
description: Use Dart as your scripting language, and register scripts from anywhere.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.17.1
  mason_logger: ^0.2.4
  path: ^1.8.3

dev_dependencies:
  apealed_analysis: ^0.0.1
  test: ^1.24.3

executables:
  dfn:
